blog/urls.py
from django.conf.urls import url

from . import views
app_name = "blog"
urlpatterns = [
    # 匹配规则，视图函数，别名
    # url(r'^$', views.index, name='index'),
    # url(r'^post/(?P<pk>[0-9]+)/$', views.detail, name='detail'),
    # url(r'^archives/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$',
    #     views.archives,
    #     name='archives'),
    # url(r'^category/(?P<pk>[0-9]+)/$', views.category, name='category'),
    # url(r'^tag/(?P<pk>[0-9]+)/$', views.tags, name='tag'),
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^post/(?P<pk>[0-9]+)/$',
        views.PostDetailView.as_view(),
        name='detail'),
    url(r'^archives/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$',
        views.ArchivesView.as_view(),
        name='archives'),
    url(r'^category/(?P<pk>[0-9]+)/$',
        views.CategoryView.as_view(),
        name='category'),
    url(r'^tag/(?P<pk>[0-9]+)/$', views.TagView.as_view(), name='tag'),
    # url(r'^search/$', views.search, name='search'),
]

comments/urls.py
# coding=utf-8
from django.conf.urls import url

from . import views

app_name = "comments"
urlpatterns = [
    url(r'^commnet/post/(?P<post_pk>[0-9]+)/$',
        views.post_comment,
        name='post_comment'),
]

xyy/urls.py
from blog.feeds import AllPostsRssFeed

from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'', include('blog.urls')),
    path(r'', include('comments.urls')),
    # 记得在顶部引入 AllPostsRssFeed
    path(r'all/rss/', AllPostsRssFeed(), name='rss'),
    path(r'search/', include('haystack.urls')),
]

blog/models.py
# coding:utf-8
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from django.utils.html import strip_tags
from django.utils.six import python_2_unicode_compatible

import markdown


# Create your models here
# 类名 对应 表名
@python_2_unicode_compatible
class Category(models.Model):
    """
    分类
    """
    # 属性名 对应列名 ；name的类型是插入
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


@python_2_unicode_compatible
class Tag(models.Model):
    """
    标签
    """
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


@python_2_unicode_compatible
class Post(models.Model):
    """
    博客内容
    """
    # 文章标题 短字符型
    title = models.CharField(max_length=70)
    # 文章内容
    body = models.TextField()
    # 文章创建时间
    created_time = models.DateTimeField()
    # 文章修改时间
    modified_time = models.DateTimeField(auto_now_add=True)
    # 文章摘要 可以为空;
    # blank=True 和 null=True 后者是数据库可以为空
    # 前者是CharField可以为空，传到数据库是空字符串
    excerpt = models.CharField(max_length=200, null=True, blank=True)
    # 分类 如果外键对应的category 被删除，则置空
    category = models.ForeignKey(
        Category, null=True, blank=True, on_delete=models.SET_NULL)
    # 标签
    tag = models.ForeignKey(
        Tag, null=True, blank=True, on_delete=models.SET_NULL)
    # 作者
    author = models.ForeignKey(
        User, null=True, blank=True, on_delete=models.SET_NULL)
    # 浏览量 PisitiveIntegerField 只允许是正整数，0
    views = models.PositiveIntegerField(default=0)

    def increase_views(self):
        """
        阅读量自增函数
        """
        self.views += 1
        self.save(update_fields=['views'])

    def __str__(self):
        return self.title

    # 自定义 get_absolute_url 方法
    # 记得从 django.urls 中导入 reverse 函数
    def get_absolute_url(self):
        return reverse('blog:detail', kwargs={'pk': self.pk})

    # 自动生成摘要
    def save(self, *args, **kwargs):
        # 如果没有填写摘要
        if not self.excerpt:
            # 首先实例化一个 Markdown 类，用于渲染 body 的文本
            md = markdown.Markdown(extensions=[
                'markdown.extensions.extra',
                'markdown.extensions.codehilite',
            ])
            # 先将 Markdown 文本渲染成 HTML 文本
            # strip_tags 去掉 HTML 文本的全部 HTML 标签
            # 从文本摘取前 54 个字符赋给 excerpt
            self.excerpt = strip_tags(md.convert(self.body))[:54]

        # 调用父类的 save 方法将数据保存到数据库中
        super(Post, self).save(*args, **kwargs)

    class Meta:
        # 负号表示逆序排列
        ordering = ['-created_time', 'title']

comments/models.py
from django.db import models
from django.utils.six import python_2_unicode_compatible


# Create your models here.
@python_2_unicode_compatible
class Comment(models.Model):
    # 评论人的名字
    name = models.CharField(max_length=100)
    # 评论人的邮件
    email = models.EmailField(max_length=255)
    # 个人网站
    url = models.URLField(blank=True)
    # 评论内容
    text = models.TextField(default='')
    # 评论时间 自动生成当前时间
    created_time = models.DateTimeField(auto_now_add=True)
    # 评论文章 级联删除
    post = models.ForeignKey('blog.post', on_delete=models.CASCADE)

blog/views.py
# coding=utf-8
import calendar
import datetime

from comments.forms import CommentForm

from django.db.models import Q
from django.shortcuts import get_object_or_404
from django.shortcuts import render
from django.utils.text import slugify
from django.views.generic import DetailView, ListView

import markdown
from markdown.extensions.toc import TocExtension

from .models import Category, Post, Tag

# from django.http import HttpResponse

# ***************************视图函数**************************
# def index(request):
#     return HttpResponse("欢迎访问我的博客首页！")
# def index(request):
#     '''
#     首页
#     '''
#     # 查询数据库，返回所有的post
#     post_list = Post.objects.all().order_by("-created_time")
#     # tag_list = Tag.objects.all()
#     return render(
#         request,
#         'blog/index.html',
#         context={
#             "title": "xyy blog",
#             "post_list": post_list,
#             # "tag_list": tag_list,
#         })

# def archives(request, year, month):
#     '''
#     归档 根据year，month 查询数据库，返回内容
#     '''
#     # post_list=Post.objects.all()
#     # dayMax = 30
#     # months = [1, 3, 5, 7, 8, 10, 12]
#     # if int(month) in months:
#     #     dayMax = 31
#     monthRange = calendar.monthrange(int(year), int(month))
#     post_list = Post.objects.filter(
#         created_time__range=(datetime.date(
#             int(year), int(month),
#             1), datetime.date(int(year), int(month), monthRange[
#                 1])))  # 在models中修改了排序规则所以不用.order_by('-created_time')
#     # post_list = Post.objects.filter(
#     #     created_time__year=year,
#     #     created_time__month=month).order_by('-created_time')
#     return render(request, 'blog/index.html',
#                   context={'post_list': post_list})

# def category(request, pk):
#     '''
#     分类
#     '''
#     cate = get_object_or_404(Category, pk=pk)
#     post_list = Post.objects.filter(category=cate).order_by('-created_time')
#     return render(request, 'blog/index.html',
#                   context={'post_list': post_list})

# def tags(request, pk):
#     '''
#     标签云
#     '''
#     tag = get_object_or_404(Tag, pk=pk)
#     post_list = Post.objects.filter(tag=tag).order_by('-created_time')
#     return render(request, 'blog/index.html',
#                   context={'post_list': post_list})

# def detail(request, pk):
#     '''
#     文章详情
#     '''
#     # 根据pk 获取文章内容，如果文章不存在，返回404
#     post = get_object_or_404(Post, pk=pk)
#     # 统计阅读数
#     post.increase_views()
#     # 记得在顶部引入 markdown 模块
#     post.body = markdown.markdown(
#         post.body,
#         extensions=[
#             'markdown.extensions.extra',
#             'markdown.extensions.codehilite',
#             'markdown.extensions.toc',
#         ])
#     # 更新detail 显示评论内容
#     # 创建表单对象
#     form = CommentForm()
#     # 获取这篇 post 下的全部评论
#     # 等价于 comment_list = comment.objects.filter(post=post)
#     comment_list = post.comment_set.all()

#     # 将文章、表单、以及文章下的评论列表作为模板变量传给 detail.html 模板，以便渲染相应数据。
#     context = {'post': post, 'form': form, 'comment_list': comment_list}
#     return render(request, 'blog/detail.html', context=context)

# ***************************视图函数**************************


# ***************************类视图函数**************************
# 继承ListView 视情况而定
# ListView是从数据库中获取某个模型列表数据
class IndexView(ListView):
    """
    继承ListView
    获取Post所有的数据
    """
    # 指定要获取数据的模型
    model = Post
    # 指定这个视图渲染的模板
    template_name = 'blog/index.html'
    # 指定获取的模型列表数据保存的变量名,这个变量会被传递给模板。
    context_object_name = 'post_list'
    # 指定 paginate_by 属性后开启分页功能，其值代表每一页包含多少篇文章
    paginate_by = 3

    def get_context_data(self, **kwargs):
        """
        在视图函数中将模板变量传递给模板是通过给 render 函数的 context 参数传递一个字典实现的，
        例如 render(request, 'blog/index.html', context={'post_list': post_list})
        这里传递了一个 {'post_list': post_list} 字典给模板。
        在类视图中，这个需要传递的模板变量字典是通过 get_context_data 获得的，
        所以我们复写该方法，以便我们能够自己再插入一些我们自定义的模板变量进去。
        """

        # 首先获得父类生成的传递给模板的字典。
        context = super().get_context_data(**kwargs)

        # 父类生成的字典中已有 paginator、page_obj、is_paginated 这三个模板变量，
        # paginator 是 Paginator 的一个实例，
        # page_obj 是 Page 的一个实例，
        # is_paginated 是一个布尔变量，用于指示是否已分页。
        # 例如如果规定每页 10 个数据，而本身只有 5 个数据，其实就用不着分页，此时 is_paginated=False。
        # 由于 context 是一个字典，所以调用 get 方法从中取出某个键对应的值。
        paginator = context.get('paginator')
        page = context.get('page_obj')
        is_paginated = context.get('is_paginated')

        # 调用自己写的 pagination_data 方法获得显示分页导航条需要的数据，见下方。
        pagination_data = self.pagination_data(paginator, page, is_paginated)

        # 将分页导航条的模板变量更新到 context 中，注意 pagination_data 方法返回的也是一个字典。
        context.update(pagination_data)

        # 将更新后的 context 返回，以便 ListView 使用这个字典中的模板变量去渲染模板。
        # 注意此时 context 字典中已有了显示分页导航条所需的数据。
        return context

    def pagination_data(self, paginator, page, is_paginated):
        if not is_paginated:
            # 如果没有分页，则无需显示分页导航条，不用任何分页导航条的数据，因此返回一个空的字典
            return {}

        # 当前页左边连续的页码号，初始值为空
        left = []

        # 当前页右边连续的页码号，初始值为空
        right = []

        # 标示第 1 页页码后是否需要显示省略号
        left_has_more = False

        # 标示最后一页页码前是否需要显示省略号
        right_has_more = False

        # 标示是否需要显示第 1 页的页码号。
        # 因为如果当前页左边的连续页码号中已经含有第 1 页的页码号，此时就无需再显示第 1 页的页码号，
        # 其它情况下第一页的页码是始终需要显示的。
        # 初始值为 False
        first = False

        # 标示是否需要显示最后一页的页码号。
        # 需要此指示变量的理由和上面相同。
        last = False

        # 获得用户当前请求的页码号
        page_number = page.number

        # 获得分页后的总页数
        total_pages = paginator.num_pages

        # 获得整个分页页码列表，比如分了四页，那么就是 [1, 2, 3, 4]
        page_range = paginator.page_range

        if page_number == 1:
            # 如果用户请求的是第一页的数据，那么当前页左边的不需要数据，因此 left=[]（已默认为空）。
            # 此时只要获取当前页右边的连续页码号，
            # 比如分页页码列表是 [1, 2, 3, 4]，那么获取的就是 right = [2, 3]。
            # 注意这里只获取了当前页码后连续两个页码，你可以更改这个数字以获取更多页码。
            right = page_range[page_number:page_number + 2]

            # 如果最右边的页码号比最后一页的页码号减去 1 还要小，
            # 说明最右边的页码号和最后一页的页码号之间还有其它页码，因此需要显示省略号，通过 right_has_more 来指示。
            if right[-1] < total_pages - 1:
                right_has_more = True

            # 如果最右边的页码号比最后一页的页码号小，说明当前页右边的连续页码号中不包含最后一页的页码
            # 所以需要显示最后一页的页码号，通过 last 来指示
            if right[-1] < total_pages:
                last = True

        elif page_number == total_pages:
            # 如果用户请求的是最后一页的数据，那么当前页右边就不需要数据，因此 right=[]（已默认为空），
            # 此时只要获取当前页左边的连续页码号。
            # 比如分页页码列表是 [1, 2, 3, 4]，那么获取的就是 left = [2, 3]
            # 这里只获取了当前页码后连续两个页码，你可以更改这个数字以获取更多页码。
            left = page_range[(page_number - 3) if (
                page_number - 3) > 0 else 0:page_number - 1]

            # 如果最左边的页码号比第 2 页页码号还大，
            # 说明最左边的页码号和第 1 页的页码号之间还有其它页码，因此需要显示省略号，通过 left_has_more 来指示。
            if left[0] > 2:
                left_has_more = True

            # 如果最左边的页码号比第 1 页的页码号大，说明当前页左边的连续页码号中不包含第一页的页码，
            # 所以需要显示第一页的页码号，通过 first 来指示
            if left[0] > 1:
                first = True
        else:
            # 用户请求的既不是最后一页，也不是第 1 页，则需要获取当前页左右两边的连续页码号，
            # 这里只获取了当前页码前后连续两个页码，你可以更改这个数字以获取更多页码。
            left = page_range[(page_number - 3) if (
                page_number - 3) > 0 else 0:page_number - 1]
            right = page_range[page_number:page_number + 2]

            # 是否需要显示最后一页和最后一页前的省略号
            if right[-1] < total_pages - 1:
                right_has_more = True
            if right[-1] < total_pages:
                last = True

            # 是否需要显示第 1 页和第 1 页后的省略号
            if left[0] > 2:
                left_has_more = True
            if left[0] > 1:
                first = True

        data = {
            'left': left,
            'right': right,
            'left_has_more': left_has_more,
            'right_has_more': right_has_more,
            'first': first,
            'last': last,
        }

        return data


# CategoryView和IndexView的属性值一样
# 所以可以继承IndexView
class CategoryView(IndexView):
    """
    从post_list中获取指定类名的数据
    """

    # 该方法默认获取指定模型的全部列表数据
    # 重写get_queryset 获取指定数据
    def get_queryset(self):
        cate = get_object_or_404(Category, pk=self.kwargs.get('pk'))
        return super(CategoryView, self).get_queryset().filter(category=cate)


class ArchivesView(IndexView):
    """
    从post_list中获取指定时间的数据
    """

    def get_queryset(self):
        # 从URL 捕获命名组参数值
        year = self.kwargs.get('year')
        month = self.kwargs.get('month')
        monthRange = calendar.monthrange(int(year), int(month))
        post_list = super(ArchivesView, self).get_queryset().filter(
            created_time__range=(
                datetime.date(int(year), int(month), 1),
                datetime.date(int(year), int(month), monthRange[1])))
        return post_list


class TagView(IndexView):
    """
    从post_list 获取指定tag的数据
    """

    def get_queryset(self):
        tag = get_object_or_404(Tag, pk=self.kwargs.get('pk'))
        post_list = super(TagView, self).get_queryset().filter(tag=tag)
        return post_list


class PostDetailView(DetailView):
    model = Post
    template_name = 'blog/detail.html'
    context_object_name = 'post'

    def get(self, request, *args, **kwargs):
        # 覆写 get 方法的目的是因为每当文章被访问一次，就得将文章阅读量 +1
        # get 方法返回的是一个 HttpResponse 实例
        # 之所以需要先调用父类的 get 方法，是因为只有当 get 方法被调用后，
        # 才有 self.object 属性，其值为 Post 模型实例，即被访问的文章 post
        response = super(PostDetailView, self).get(request, *args, **kwargs)

        # 将文章阅读量 +1
        # 注意 self.object 的值就是被访问的文章 post
        self.object.increase_views()

        # 视图必须返回一个 HttpResponse 对象
        return response

    def get_object(self, queryset=None):
        # 覆写 get_object 方法的目的是因为需要对 post 的 body 值进行渲染
        post = super(PostDetailView, self).get_object(queryset=None)
        md = markdown.Markdown(extensions=[
            'markdown.extensions.extra',
            'markdown.extensions.codehilite',

templates/blog/about.html
<!DOCTYPE html>
<html>
	<head>
		<title>Black &amp; White</title>

		<!-- meta -->
		<meta charset="UTF-8">
	    <meta name="viewport" content="width=device-width, initial-scale=1">

	    <!-- css -->
		<link rel="stylesheet" href="css/bootstrap.min.css">
		<link rel="stylesheet" href="css/ionicons.min.css">
		<link rel="stylesheet" href="css/pace.css">
	    <link rel="stylesheet" href="css/custom.css">

	    <!-- js -->
	    <script src="js/jquery-2.1.3.min.js"></script>
	    <script src="js/bootstrap.min.js"></script>
	    <script src="js/pace.min.js"></script>
	    <script src="js/modernizr.custom.js"></script>
	</head>

	<body id="page">
		<div class="container">	
			<header id="site-header">
				<div class="row">
					<div class="col-md-4 col-sm-5 col-xs-8">
						<div class="logo">
							<h1><a href="index.html"><b>Black</b> &amp; White</a></h1>
						</div>
					</div><!-- col-md-4 -->
					<div class="col-md-8 col-sm-7 col-xs-4">
						<nav class="main-nav" role="navigation">
							<div class="navbar-header">
  								<button type="button" id="trigger-overlay" class="navbar-toggle">
    								<span class="ion-navicon"></span>
  								</button>
							</div>

							<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
  								<ul class="nav navbar-nav navbar-right">
    								<li class="cl-effect-11"><a href="index.html" data-hover="Home">Home</a></li>
    								<li class="cl-effect-11"><a href="full-width.html" data-hover="Blog">Blog</a></li>
    								<li class="cl-effect-11"><a href="about.html" data-hover="About">About</a></li>
    								<li class="cl-effect-11"><a href="contact.html" data-hover="Contact">Contact</a></li>
  								</ul>
							</div><!-- /.navbar-collapse -->
						</nav>
						<div id="header-search-box">
							<a id="search-menu" href="#"><span id="search-icon" class="ion-ios-search-strong"></span></a>
							<div id="search-form" class="search-form">
								<form role="search" method="get" id="searchform" action="#">
									<input type="search" placeholder="Search" required>
									<button type="submit"><span class="ion-ios-search-strong"></span></button>
								</form>				
							</div>
						</div>
					</div><!-- col-md-8 -->
				</div>
			</header>
		</div>

		<div class="content-body">
			<div class="container">
				<div class="row">
					<main class="col-md-12">
						<h1 class="page-title">About Me</h1>
						<article class="post">
							<div class="entry-content clearfix">
								<figure class="img-responsive-center">
									<img class="img-responsive" src="img/me.jpg" alt="Developer Image">
								</figure>
								<p>Responsive web design offers us a way forward, finally allowing us to design for the ebb and flow of things. There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don’t look even slightly.</p>
								<p>Responsive web design offers us a way forward, finally allowing us to design for the ebb and flow of things. There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don’t look even slightly.</p>
								<div class="height-40px"></div>
								<h2 class="title text-center">Social</h2>
								<ul class="social">
									<li class="facebook"><a href="#"><span class="ion-social-facebook"></span></a></li>
									<li class="twitter"><a href="#"><span class="ion-social-twitter"></span></a></li>
									<li class="google-plus"><a href="#"><span class="ion-social-googleplus"></span></a></li>
									<li class="tumblr"><a href="#"><span class="ion-social-tumblr"></span></a></li>
								</ul>
							</div>
						</article>
					</main>
				</div>
			</div>
		</div>
		<footer id="site-footer">
			<div class="container">
				<div class="row">
					<div class="col-md-12">
						<p class="copyright">&copy; 2014 ThemeWagon.com</p>
					</div>
				</div>
			</div>
		</footer>

		<!-- Mobile Menu -->
		<div class="overlay overlay-hugeinc">
			<button type="button" class="overlay-close"><span class="ion-ios-close-empty"></span></button>
			<nav>
				<ul>
					<li><a href="index.html">Home</a></li>
					<li><a href="full-width.html">Blog</a></li>
					<li><a href="about.html">About</a></li>
					<li><a href="contact.html">Contact</a></li>
				</ul>
			</nav>
		</div>

		<script src="js/script.js"></script>
		
	</body>
</html>

templates/blog/detail.html
{% extends 'base.html' %}
<!-- 文章内容 -->
{% block main %}
    <article class="post post-{{ post.pk }}">
        <header class="entry-header">
            <h1 class="entry-title">{{ post.title }}</h1>
            <div class="entry-meta">
                <span class="post-category">
                    <a href="#">{{ post.category.name }}</a>
                </span>
                <span class="post-date">
                    <a href="#">
                        <time class="entry-date" datetime="{{ post.created_time }}">{{ post.created_time }}</time>
                    </a>
                </span>
                <span class="post-author">
                    <a href="#">{{ post.author }}</a>
                </span>
                <span class="comments-link">
                    <!-- {{ post.comment_set_count }} 评论 -->
                    <a href="#">{{ post.comment_set_count }} 评论</a>
                </span>
                <span class="views-count">
                    <!-- {{ post.views }}阅读 -->
                    <a href="#">{{ post.views }}阅读</a>
                </span>
            </div>
        </header>
        <div class="entry-content clearfix">
            {{ post.body|safe }}
        </div>
    </article>
    <!-- 文章评论区 -->
    <section class="comment-area" id="comment-area">
        <hr>
        <h3>发表评论</h3>
        <form action="{% url 'comments:post_comment' post.pk %}" method="post" class="comment-form">
            {% csrf_token %}
            <div class="row">
                <div class="col-md-4">
                    <label for="{{ form.name.id_for_label }}">名字：</label>
                    {{ form.name }} {{ form.name.errors }}
                </div>
                <div class="col-md-4">
                    <label for="{{ form.email.id_for_label }}">邮箱：</label>
                    {{ form.email }} {{ form.email.errors }}
                </div>
                <div class="col-md-4">
                    <label for="{{ form.url.id_for_label }}">URL：</label>
                    {{ form.url }} {{ form.url.errors }}
                </div>
                <div class="col-md-12">
                    <label for="{{ form.text.id_for_label }}">评论：</label>
                    {{ form.text }} {{ form.text.errors }}
                    <button type="submit" class="comment-btn">发表</button>
                </div>
            </div>
            <!-- row -->
        </form>

        <ul class="comment-list list-unstyled">
            {% for comment in comment_list %}
            <li class="comment-item">
                <span class="nickname">{{ comment.name }}</span>
                <time class="submit-date">{{ comment.created_time }}</time>
                <div class="text">
                    {{ comment.text }}
                </div>
            </li>
            {% empty %} 暂无评论 {% endfor %}
        </ul>
    </section>
{% endblock main %}
<!-- 自动生成文章目录 -->
{% block toc %}
    <div class="widget widget-content">
            <h3 class="widget-title">文章目录</h3>
            {{ post.toc|safe }}
    </div>
{% endblock toc %}

templates/blog/index.html
{% extends 'base.html' %} 
{% block main %} 
    {% if error_msg %}
        <p>{{ error_msg }}</p>
    {% endif %}
    
    <!-- 遍历文章内容 -->
    {% for post in post_list %}
        <article class="post post-{{ post.pk }}">
            <h1 class="entry-title">
                <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                <!-- <a href="{% url 'blog:detail' post.pk %}">{{ post.title }}</a> -->
            </h1>

            <div class="entry-meta">
                <!-- 分类 -->
                <span class="post-category">
                    <a href="{% url 'blog:category' post.category.pk %}">{{ post.category.name }}</a>
                </span>
                <!-- 归档 -->
                <span class="post-date">
                    <a href="{% url 'blog:archives' post.created_time.year post.created_time.month %}">
                        <time class="entry-date" datetime="{{ post.created_time }}">{{ post.created_time }}</time>
                    </a>
                </span>
                <span class="post-author">
                    <a href="#">{{ post.author }}</a>
                </span>
                <span class="comments-link">
                    <a href="{%  url 'comments:post_comment' post.pk %}">{{ post.comment_set.count }} 评论</a>
                </span>
                <span class="views-count">
                    <a href="#">{{ post.views }} 阅读</a>
                </span>

                <div class="entry-content clearfix">
                    <p>{{ post.excerpt }}</p>
                    <!-- 下面这种方法 如果是markdown 会显示符号 -->
                    <!-- <p>{{ post.body|truncatechars:54 }}</p> -->
                    <div class="read-more cl-effect-14">
                        <a href="{{ post.get_absolute_url}} " class="more-link">继续阅读
                            <span class="meta-nav">→</span>
                        </a>
                    </div>
                </div>

            </div>
        </article>
    {% empty %}
        <div class="no-post">暂时还没有发布的文章！</div>
    {% endfor %}

    <!-- 分页效果 -->
    {% if is_paginated %}
        <div class="pagination">
            {% if first %}
                <a href="?page=1">1</a>
            {% endif %} 
            {% if left %} 
                {% if left_has_more %}
                    <span>...</span>
            {% endif %} 
            {% for i in left %}
                <a href="?page={{ i }}">{{ i }}</a>
            {% endfor %} 
            {% endif %}
                <!-- <a href="?page={{ page_obj.number }}" style="color: red">{{ page_obj.number }}</a> -->
                <a class="current-page" href="?page={{ page_obj.number }}">{{ page_obj.number }}</a>
            {% if right %} 
                {% for i in right %}
                    <a href="?page={{ i }}">{{ i }}</a>
            {% endfor %} 
            {% if right_has_more %}
                <span>...</span>
            {% endif %} 
            {% endif %} 
                {% if last %}
                    <a href="?page={{ paginator.num_pages }}">{{ paginator.num_pages }}</a>
            {% endif %}
        </div>
    {% endif %} 
{% endblock main %}